<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite hostname="gipl180" name="Default test" tests="2" failures="1" timestamp="12 Mar 2021 13:03:06 GMT" time="12.919" errors="0">
  <testcase name="open_login_page" time="4.643" classname="AdvanceSelenium.Signup_Script"/>
  <testcase name="invalid_email" time="1.26" classname="AdvanceSelenium.Signup_Script">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:482)
	at AdvanceSelenium.Signup_Script.invalid_email(Signup_Script.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- invalid_email -->
=======
<testsuite hostname="gipl-207" ignored="5" name="Default test" tests="1" failures="0" timestamp="15 Mar 2021 09:12:37 GMT" time="18.452" errors="0">
  <testcase name="testNew" time="2.939" classname="AdvanceSelenium.Homepage"/>
  <testcase name="loggingOutput" time="0.0" classname="AdvanceSelenium.Homepage">
    <ignored/>
  </testcase> <!-- loggingOutput -->
  <testcase name="validateHeaderLinks" time="0.0" classname="AdvanceSelenium.Homepage">
    <ignored/>
  </testcase> <!-- validateHeaderLinks -->
  <testcase name="getFromExcel" time="0.0" classname="AdvanceSelenium.Homepage">
    <ignored/>
  </testcase> <!-- getFromExcel -->
  <testcase name="validatePopUP" time="0.0" classname="AdvanceSelenium.Homepage">
    <ignored/>
  </testcase> <!-- validatePopUP -->
  <testcase name="brokenLinks" time="0.0" classname="AdvanceSelenium.Homepage">
    <ignored/>
  </testcase> <!-- brokenLinks -->
>>>>>>> aa042e4fb4eb3a4489d15fba512bd48c48ba9f70
</testsuite> <!-- Default test -->
